### PR TITLE
Merge gateway KMIA layout

### PR DESCRIPTION
**Pull request by legoboyvdlp**
This layout was updated in 2015 by sstoeckle.
No gaps at all around airport.

Best
Legoboy

### CODE REVIEW

**Comment by FGDATA** [comment]
Thanks Lego
I will take a look and merge subsequently.
would you mind pasting here an image of end result?
IH-COL

**Comment by legoboyvdlp** [comment]
Sure -- not much difference, but it is a little better than TerraSync.

**Comment by legoboyvdlp** [comment]
fgfs-screen-022

Not much difference.

Note that I have not finished cloning the objects.

**Comment by legoboyvdlp** [comment]
Image upload failed

**Comment by FGDATA** [comment]
Looks pUrfect. :grinning:

**Pull request merged**
